### PR TITLE
Add function to compute the modular exponentiation for BigInts

### PR DESCRIPTION
**Pull request by kunerd**
Implementation of the 'Left-to-right k-ary exponentiation' algorithm.

### CODE REVIEW

**Comment by kunerd** [comment]
Hi, this is my first pull request to a rust library. It definitely needs some documentation, but I thought it would be better to wait for some feedback first and add the documentation at the end.

**Comment by alexcrichton** [comment]
Unfortunately I'm pretty unfamiliar with the implementation here, so it may be best to put this as an extension trait on crates.io instead of an extension trait in-tree.

**Comment by kunerd** [comment]
It is an implementation of the LR-k-ary algorithm as described in the "[Handbook of Applied Cryptography](http://cacr.uwaterloo.ca/hac/about/chap14.pdf), 14.82".

Your idea to put this as an extension trait to crates.io is also OK for me.

**Comment by alexcrichton** [comment]
Ok, let's take that strategy for now, thanks regardless for the PR though!

**Pull request closed without merging**
